/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dryca;

import java.util.Random;

/**
 *
 * @author Wendrya
 */
public class BiscoitoDaSorte extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public BiscoitoDaSorte() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbsortear = new javax.swing.JButton();
        jlsortedodia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Biscoito da Sorte");

        jbsortear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jbsortear.setText("Sortear");
        jbsortear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbsortearMouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Sua frase do dia é:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(175, 175, 175)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jlsortedodia, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(238, 238, 238)
                        .addComponent(jbsortear)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(62, 62, 62)
                .addComponent(jLabel2)
                .addGap(82, 82, 82)
                .addComponent(jlsortedodia, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
                .addComponent(jbsortear)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jbsortearMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        
        Random gerador = new Random();
        int a = gerador.nextInt(29);
        jlsortedodia.setText(String.valueOf(a));
        
        if (a==0) {
            jlsortedodia.setText(String.valueOf("A vida trará coisas boas se tiveres paciência."));
        }    
        
        if (a==1) {
            jlsortedodia.setText(String.valueOf("Demonstre amor e alegria em todas as oportunidades e verás que a paz nasce dentro de você."));
        }
        
        if (a==2) {
            jlsortedodia.setText(String.valueOf("Não compense na ira o que lhe falta na razão."));
        }    
        
        if (a==3) {
            jlsortedodia.setText(String.valueOf("Defeitos e virtudes são apenas dois lados da mesma moeda."));
        }    
        
        if (a==4) {
            jlsortedodia.setText(String.valueOf("A maior de todas as torres começa no solo."));
        }    
        
        if (a==5) {
            jlsortedodia.setText(String.valueOf("Não há que ser forte. Há que ser flexível."));
        }    
        
        if (a==6) {
            jlsortedodia.setText(String.valueOf("A gente todo dia arruma os cabelos, por que não o coração?"));
        }
        
        if (a==7) {
            jlsortedodia.setText(String.valueOf("Há três coisas que jamais voltam; a flecha lançada, a palavra dita e a oportunidade perdida."));
        }    
        
        if (a==8) {
            jlsortedodia.setText(String.valueOf("A juventude não é uma época da vida, é um estado de espírito."));
        }    
        
        if (a==9) {
            jlsortedodia.setText(String.valueOf("Podemos escolher o que semear, mas somos obrigados a colher o que plantamos."));
        }    
        
        if (a==10) {
            jlsortedodia.setText(String.valueOf("Dê toda a atenção para a formação dos teus filhos, sobretudo por exemplos de tua própria vida."));
        }    
        
        if (a==11) {
            jlsortedodia.setText(String.valueOf("Siga os bons e aprenda com eles."));
        }
        
        if (a==12) {
            jlsortedodia.setText(String.valueOf("Não importa o tamanho da montanha, ela não pode tapar o sol."));
        }    
        
        if (a==13) {
            jlsortedodia.setText(String.valueOf("O bom-senso vai mais longe do que muito conhecimento."));
        }    
        
        if (a==14) {
            jlsortedodia.setText(String.valueOf("Quem quer colher rosas deve suportar os espinhos."));
        }    
        
        if (a==15) {
            jlsortedodia.setText(String.valueOf("São os nossos amigos que nos ensinam as mais valiosas lições."));
        }    
        
        if (a==16) {
            jlsortedodia.setText(String.valueOf("Uma iniciativa mal-sucedida não significa o final de tudo. Sempre existe uma nova oportunidade."));
        }
        
        if (a==17) {
            jlsortedodia.setText(String.valueOf("Aquele que se importa com o sentimento dos outros, não é um tolo."));
        }    
        
        if (a==18) {
            jlsortedodia.setText(String.valueOf("A adversidade é um espelho que reflete o verdadeiro eu."));
        }    
        
        if (a==19) {
            jlsortedodia.setText(String.valueOf("Lamentar aquilo que não temos é desperdiçar aquilo que já possuímos."));
        }    
        
        if (a==20) {
            jlsortedodia.setText(String.valueOf("Uma bela flor é incompleta sem suas folhas."));
        }    
        
        if (a==21) {
            jlsortedodia.setText(String.valueOf("Sem o fogo do entusiasmo, não há o calor da vitória."));
        }
        
        if (a==22) {
            jlsortedodia.setText(String.valueOf("Não há melhor negócio que a vida. A gente há obtém a troco de nada."));
        }    
        
        if (a==23) {
            jlsortedodia.setText(String.valueOf("O riso é a menor distância entre duas pessoas."));
        }    
        
        if (a==24) {
            jlsortedodia.setText(String.valueOf("Você é jovem apenas uma vez. Depois precisa inventar outra desculpa."));
        }    
        
        if (a==25) {
            jlsortedodia.setText(String.valueOf("É mais fácil conseguir o perdão do que a permissão."));
        }    
        
        if (a==26) {
            jlsortedodia.setText(String.valueOf("Os defeitos são mais fortes quando o amor é fraco."));
        }
        
        if (a==27) {
            jlsortedodia.setText(String.valueOf("Amizade e Amor são coisas que podem virar uma só num piscar de olhos."));
        }    
        
        if (a==28) {
            jlsortedodia.setText(String.valueOf("Surpreender e ser surpreendido é o segredo do amor."));
        }    
        
        if (a==29) {
            jlsortedodia.setText(String.valueOf("Faça pequenas coisas agora e maiores coisas lhe serão confiadas cada dia."));
        }    
       
        
        
        
        
        
        
        
        
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiscoitoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiscoitoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiscoitoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiscoitoDaSorte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiscoitoDaSorte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbsortear;
    private javax.swing.JLabel jlsortedodia;
    // End of variables declaration                   
}
